# Generated by Django 3.1.7 on 2021-03-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(auto_now=True)),
                ('todo_text', models.CharField(default='N/A', max_length=500)),
                ('todo_title', models.CharField(default='N/A', max_length=200)),
                ('todo_image', models.TextField(default='//im0-tub-com.yandex.net/i?id=464bd9957551dd9b469f98aa1fa2f6e0&n=13')),
            ],
        ),
    ]
